# Generated by Django 4.2 on 2025-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_token', models.CharField(editable=False, max_length=500, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
