# Generated by Django 4.2 on 2025-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tokenrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrecord',
            name='temporary_token',
            field=models.TextField(),
        ),
    ]
