# Generated by Django 4.2 on 2025-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tokenrecord_temporary_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrecord',
            name='is_used',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
